ENH: require C++14 for examples
First warning and first error (of about 50):

Modules/Core/Common/itkConfigure.h:56:6: warning: #warning "WARNING:  The current project is configured to use a C++ standard version older than the C++ standard used for this build of ITK" [-Wcpp]

Modules/Core/Common/include/itkSize.h:329:29: error: 'constexpr const value_type& itk::Size<VDimension>::operator[](itk::Size<VDimension>::size_type) const' cannot be overloaded