COMP: fix compile errors by aggressive code cleanup
The errors were introduced by 89a73005fac92e1364c2e3e3ccd7492c99fb446f.

/home/runner/work/Ex/src/Filtering/LabelMap/ShapeAttributesForBinaryImage/Code.cxx: In function 'int main(int, char**)':
/home/runner/work/Ex/src/Filtering/LabelMap/ShapeAttributesForBinaryImage/Code.cxx:48:16: error: 'argv' was not declared in this scope
     fileName = argv[1];
                ^~~~

../src/Filtering/Thresholding/DemonstrateThresholdAlgorithms/Code.cxx:52:0: error: unterminated #ifdef